//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRegister.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Assignment
    {
        public int id { get; set; }

        [Display(Name = "Course Id")]
        public int courseId { get; set; }

        [Display(Name = "Assignment's Name")]
        public string name { get; set; }

        [Display(Name = "Assignment's Description")]
        public string description { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dueDate { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
