//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRegister.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public string id { get; set; }

        [Display(Name = "Faculty's First Name")]
        public string firstName { get; set; }

        [Display(Name = "Faculty's Last Name")]
        public string lastName { get; set; }

        [Display(Name = "Faculty's Email")]
        public string email { get; set; }

        [ForeignKey("Department")]
        [Display(Name = "Department Id")]
        public int departmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }

        public virtual Department Department { get; set; }
    }
}
